version: '3.8'

services:
  app:
    build: .
    container_name: gcp-chatbot
    env_file:
      - .env
    volumes:
      - ./service-account.json:/app/service-account.json:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
